/* Generated By:JavaCC: Do not edit this line. GramaticaConstants.java */
package analizador.descendente;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GramaticaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTEGER = 11;
  /** RegularExpression Id. */
  int NUMERIC = 12;
  /** RegularExpression Id. */
  int WHILE = 13;
  /** RegularExpression Id. */
  int IF = 14;
  /** RegularExpression Id. */
  int ELSE = 15;
  /** RegularExpression Id. */
  int PCOMA = 16;
  /** RegularExpression Id. */
  int PARINI = 17;
  /** RegularExpression Id. */
  int PAREND = 18;
  /** RegularExpression Id. */
  int CORI = 19;
  /** RegularExpression Id. */
  int CORD = 20;
  /** RegularExpression Id. */
  int LLAVEI = 21;
  /** RegularExpression Id. */
  int LLAVED = 22;
  /** RegularExpression Id. */
  int MAS = 23;
  /** RegularExpression Id. */
  int MENOS = 24;
  /** RegularExpression Id. */
  int POR = 25;
  /** RegularExpression Id. */
  int DIV = 26;
  /** RegularExpression Id. */
  int IGUAL = 27;
  /** RegularExpression Id. */
  int MENORQUE = 28;
  /** RegularExpression Id. */
  int MAYORQUE = 29;
  /** RegularExpression Id. */
  int MENORIGUAL = 30;
  /** RegularExpression Id. */
  int MAYORIGUAL = 31;
  /** RegularExpression Id. */
  int IGUALA = 32;
  /** RegularExpression Id. */
  int DIFERENTEDE = 33;
  /** RegularExpression Id. */
  int AND = 34;
  /** RegularExpression Id. */
  int OR = 35;
  /** RegularExpression Id. */
  int NOT = 36;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 37;
  /** RegularExpression Id. */
  int STRING = 40;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_LINE_COMMENT = 1;
  /** Lexical state. */
  int MULTI_LINE_COMMENT = 2;
  /** Lexical state. */
  int STRING_STATE = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"#*\"",
    "\"#\"",
    "\"\\n\"",
    "<token of kind 8>",
    "\"#*\"",
    "<token of kind 10>",
    "<INTEGER>",
    "<NUMERIC>",
    "\"while\"",
    "\"if\"",
    "\"else\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "<IDENTIFICADOR>",
    "\"\\\"\"",
    "<token of kind 39>",
    "\"\\\"\"",
  };

}
