/* Generated By:JavaCC: Do not edit this line. GramaticaConstants.java */
package analizador.descendente;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GramaticaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTEGER = 11;
  /** RegularExpression Id. */
  int NUMERIC = 12;
  /** RegularExpression Id. */
  int BOOLEAN = 13;
  /** RegularExpression Id. */
  int NULL = 14;
  /** RegularExpression Id. */
  int WHILE = 15;
  /** RegularExpression Id. */
  int IF = 16;
  /** RegularExpression Id. */
  int ELSE = 17;
  /** RegularExpression Id. */
  int COMA = 18;
  /** RegularExpression Id. */
  int PCOMA = 19;
  /** RegularExpression Id. */
  int PARINI = 20;
  /** RegularExpression Id. */
  int PAREND = 21;
  /** RegularExpression Id. */
  int CORI = 22;
  /** RegularExpression Id. */
  int CORD = 23;
  /** RegularExpression Id. */
  int LLAVEI = 24;
  /** RegularExpression Id. */
  int LLAVED = 25;
  /** RegularExpression Id. */
  int MAS = 26;
  /** RegularExpression Id. */
  int MENOS = 27;
  /** RegularExpression Id. */
  int POR = 28;
  /** RegularExpression Id. */
  int DIV = 29;
  /** RegularExpression Id. */
  int MODULO = 30;
  /** RegularExpression Id. */
  int IGUAL = 31;
  /** RegularExpression Id. */
  int MENORQUE = 32;
  /** RegularExpression Id. */
  int MAYORQUE = 33;
  /** RegularExpression Id. */
  int MENORIGUAL = 34;
  /** RegularExpression Id. */
  int MAYORIGUAL = 35;
  /** RegularExpression Id. */
  int IGUALA = 36;
  /** RegularExpression Id. */
  int DIFERENTEDE = 37;
  /** RegularExpression Id. */
  int AND = 38;
  /** RegularExpression Id. */
  int OR = 39;
  /** RegularExpression Id. */
  int NOT = 40;
  /** RegularExpression Id. */
  int QUESTION_MARK = 41;
  /** RegularExpression Id. */
  int DOS_PUNTOS = 42;
  /** RegularExpression Id. */
  int FUNCION = 43;
  /** RegularExpression Id. */
  int RETORNO = 44;
  /** RegularExpression Id. */
  int IDENTIFICADOR_LETRA = 45;
  /** RegularExpression Id. */
  int STRING = 49;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_LINE_COMMENT = 1;
  /** Lexical state. */
  int MULTI_LINE_COMMENT = 2;
  /** Lexical state. */
  int STRING_STATE = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"#*\"",
    "\"#\"",
    "\"\\n\"",
    "<token of kind 8>",
    "\"#*\"",
    "<token of kind 10>",
    "<INTEGER>",
    "<NUMERIC>",
    "<BOOLEAN>",
    "\"null\"",
    "\"while\"",
    "\"if\"",
    "\"else\"",
    "\",\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "\"&\"",
    "\"|\"",
    "\"!\"",
    "\"?\"",
    "\":\"",
    "\"function\"",
    "\"return\"",
    "<IDENTIFICADOR_LETRA>",
    "\"\\\"\"",
    "\"\\\\\\\"\"",
    "<token of kind 48>",
    "\"\\\"\"",
  };

}
