/* Generated By:JavaCC: Do not edit this line. GramaticaConstants.java */
package analizador.descendente;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GramaticaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTEGER = 11;
  /** RegularExpression Id. */
  int NUMERIC = 12;
  /** RegularExpression Id. */
  int BOOLEAN = 13;
  /** RegularExpression Id. */
  int NULL = 14;
  /** RegularExpression Id. */
  int FOR = 15;
  /** RegularExpression Id. */
  int IN = 16;
  /** RegularExpression Id. */
  int DO = 17;
  /** RegularExpression Id. */
  int WHILE = 18;
  /** RegularExpression Id. */
  int SWITCH = 19;
  /** RegularExpression Id. */
  int CASE = 20;
  /** RegularExpression Id. */
  int DEFAULT_WORD = 21;
  /** RegularExpression Id. */
  int IF = 22;
  /** RegularExpression Id. */
  int ELSE = 23;
  /** RegularExpression Id. */
  int COMA = 24;
  /** RegularExpression Id. */
  int PCOMA = 25;
  /** RegularExpression Id. */
  int PARINI = 26;
  /** RegularExpression Id. */
  int PAREND = 27;
  /** RegularExpression Id. */
  int CORI = 28;
  /** RegularExpression Id. */
  int CORD = 29;
  /** RegularExpression Id. */
  int LLAVEI = 30;
  /** RegularExpression Id. */
  int LLAVED = 31;
  /** RegularExpression Id. */
  int MAS = 32;
  /** RegularExpression Id. */
  int MENOS = 33;
  /** RegularExpression Id. */
  int POR = 34;
  /** RegularExpression Id. */
  int DIV = 35;
  /** RegularExpression Id. */
  int MODULO = 36;
  /** RegularExpression Id. */
  int IGUAL = 37;
  /** RegularExpression Id. */
  int MENORQUE = 38;
  /** RegularExpression Id. */
  int MAYORQUE = 39;
  /** RegularExpression Id. */
  int MENORIGUAL = 40;
  /** RegularExpression Id. */
  int MAYORIGUAL = 41;
  /** RegularExpression Id. */
  int IGUALA = 42;
  /** RegularExpression Id. */
  int DIFERENTEDE = 43;
  /** RegularExpression Id. */
  int AND = 44;
  /** RegularExpression Id. */
  int OR = 45;
  /** RegularExpression Id. */
  int NOT = 46;
  /** RegularExpression Id. */
  int QUESTION_MARK = 47;
  /** RegularExpression Id. */
  int DOS_PUNTOS = 48;
  /** RegularExpression Id. */
  int FUNCION = 49;
  /** RegularExpression Id. */
  int RETORNO = 50;
  /** RegularExpression Id. */
  int BREAK = 51;
  /** RegularExpression Id. */
  int CONTINUE = 52;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 53;
  /** RegularExpression Id. */
  int STRING = 56;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_LINE_COMMENT = 1;
  /** Lexical state. */
  int MULTI_LINE_COMMENT = 2;
  /** Lexical state. */
  int STRING_STATE = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"#*\"",
    "\"#\"",
    "\"\\n\"",
    "<token of kind 8>",
    "\"*#\"",
    "<token of kind 10>",
    "<INTEGER>",
    "<NUMERIC>",
    "<BOOLEAN>",
    "\"null\"",
    "\"for\"",
    "\"in\"",
    "\"do\"",
    "\"while\"",
    "\"switch\"",
    "\"case\"",
    "\"default\"",
    "\"if\"",
    "\"else\"",
    "\",\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "\"&\"",
    "\"|\"",
    "\"!\"",
    "\"?\"",
    "\":\"",
    "\"function\"",
    "\"return\"",
    "\"break\"",
    "\"continue\"",
    "<IDENTIFICADOR>",
    "\"\\\"\"",
    "<token of kind 55>",
    "\"\\\"\"",
  };

}
